### ISSUE TITLE
Empty error message when saving datasource - Sumo connection failed

### ISSUE THREAD

**Issue by eaglejohn81** [SumoLogic-Labs/sumologic-metrics-grafana-datasource#13]
Installed the plugin using Grafana 4..6.3

Get empty error message when saving datasource:

![image](https://user-images.githubusercontent.com/34067383/41085814-524573a4-6a38-11e8-8215-7a8a14447b68.png)

On Dashboard it shows: 
{
  "message": "Invalid username or password"
}

However, the access id/key are correct generated from SumoLogic and the api endpoint seems to be correct.

Any idea?

Thanks!

**Comment by akononenko-sumo** [comment]
Closing this as we dropped support for the old version of the Grafana. @eaglejohn81 if this issue occurs now please rise a new issue, thank you!
