### ISSUE TITLE
Empty error message when saving datasource on  Grafana 6.X

### ISSUE THREAD

**Issue by ashoktmw** [SumoLogic-Labs/sumologic-metrics-grafana-datasource#17]
I've installed sumologic plugin in Grafana 6.4 version and its not working.

Error is not actually displayed in Front end.When i configure the datasource in Grafana and click "save and test", it should save the config and display the message Datasource successfully connected. (this is expected)
But, I'm not getting the datasource connection successful, rather i'm getting nothing.

**Comment by akononenko-sumo** [comment]
Closing this as we dropped support for old versions of the Grafana.
