### ISSUE TITLE
Basic Auth Failed error

### ISSUE THREAD

**Issue by pavana-gupta** [SumoLogic-Labs/sumologic-metrics-grafana-datasource#19]
On adding sumologic data source, I am specifying "https://api.sumologic.com/api/v1" as the URL. I am also adding correct access id and keys.
However, a empty error message is received on saving the data source.

Later, while adding sumo logic query to dashboard, I am getting "Basic Auth Failed" error (even though running the same query through Postman gives me the correct result)

**Comment by akononenko-sumo** [comment]
I'm closing this issue as more than 2 years past since it was open. If you still experience issues with authorization, please open new issue.
